# Generated by Django 4.0.1 on 2022-02-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emaildata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('useremail', models.EmailField(max_length=254)),
                ('emailpassword', models.CharField(max_length=100)),
                ('sheetid', models.CharField(max_length=10000)),
                ('mailsubject', models.CharField(max_length=500)),
                ('mailmessage', models.CharField(max_length=10000)),
                ('attachment', models.FileField(upload_to='mailattachment/')),
            ],
        ),
    ]
